// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: downloaderv1/downloader.proto

package downloaderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	SavePath      string                 `protobuf:"bytes,2,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Paused        bool                   `protobuf:"varint,4,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTorrentRequest) Reset() {
	*x = AddTorrentRequest{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTorrentRequest) ProtoMessage() {}

func (x *AddTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTorrentRequest.ProtoReflect.Descriptor instead.
func (*AddTorrentRequest) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{0}
}

func (x *AddTorrentRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *AddTorrentRequest) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *AddTorrentRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AddTorrentRequest) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type AddTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InfoHash      string                 `protobuf:"bytes,3,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTorrentResponse) Reset() {
	*x = AddTorrentResponse{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTorrentResponse) ProtoMessage() {}

func (x *AddTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTorrentResponse.ProtoReflect.Descriptor instead.
func (*AddTorrentResponse) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{1}
}

func (x *AddTorrentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddTorrentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddTorrentResponse) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

type RemoveTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeleteFiles   bool                   `protobuf:"varint,2,opt,name=delete_files,json=deleteFiles,proto3" json:"delete_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTorrentRequest) Reset() {
	*x = RemoveTorrentRequest{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTorrentRequest) ProtoMessage() {}

func (x *RemoveTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTorrentRequest.ProtoReflect.Descriptor instead.
func (*RemoveTorrentRequest) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveTorrentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveTorrentRequest) GetDeleteFiles() bool {
	if x != nil {
		return x.DeleteFiles
	}
	return false
}

type RemoveTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTorrentResponse) Reset() {
	*x = RemoveTorrentResponse{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTorrentResponse) ProtoMessage() {}

func (x *RemoveTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTorrentResponse.ProtoReflect.Descriptor instead.
func (*RemoveTorrentResponse) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{3}
}

type GetTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTorrentRequest) Reset() {
	*x = GetTorrentRequest{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTorrentRequest) ProtoMessage() {}

func (x *GetTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTorrentRequest.ProtoReflect.Descriptor instead.
func (*GetTorrentRequest) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{4}
}

func (x *GetTorrentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torrent       *TorrentInfo           `protobuf:"bytes,1,opt,name=torrent,proto3" json:"torrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTorrentResponse) Reset() {
	*x = GetTorrentResponse{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTorrentResponse) ProtoMessage() {}

func (x *GetTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTorrentResponse.ProtoReflect.Descriptor instead.
func (*GetTorrentResponse) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{5}
}

func (x *GetTorrentResponse) GetTorrent() *TorrentInfo {
	if x != nil {
		return x.Torrent
	}
	return nil
}

type ListTorrentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTorrentsRequest) Reset() {
	*x = ListTorrentsRequest{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTorrentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTorrentsRequest) ProtoMessage() {}

func (x *ListTorrentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTorrentsRequest.ProtoReflect.Descriptor instead.
func (*ListTorrentsRequest) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{6}
}

func (x *ListTorrentsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListTorrentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torrents      []*TorrentInfo         `protobuf:"bytes,1,rep,name=torrents,proto3" json:"torrents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTorrentsResponse) Reset() {
	*x = ListTorrentsResponse{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTorrentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTorrentsResponse) ProtoMessage() {}

func (x *ListTorrentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTorrentsResponse.ProtoReflect.Descriptor instead.
func (*ListTorrentsResponse) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{7}
}

func (x *ListTorrentsResponse) GetTorrents() []*TorrentInfo {
	if x != nil {
		return x.Torrents
	}
	return nil
}

type TorrentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InfoHash      string                 `protobuf:"bytes,3,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Downloaded    int64                  `protobuf:"varint,5,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	Progress      float64                `protobuf:"fixed64,6,opt,name=progress,proto3" json:"progress,omitempty"`
	Peers         int32                  `protobuf:"varint,7,opt,name=peers,proto3" json:"peers,omitempty"`
	Seeders       int32                  `protobuf:"varint,8,opt,name=seeders,proto3" json:"seeders,omitempty"`
	UploadRate    int32                  `protobuf:"varint,9,opt,name=upload_rate,json=uploadRate,proto3" json:"upload_rate,omitempty"`
	DownloadRate  int32                  `protobuf:"varint,10,opt,name=download_rate,json=downloadRate,proto3" json:"download_rate,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	SavePath      string                 `protobuf:"bytes,13,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	Label         string                 `protobuf:"bytes,14,opt,name=label,proto3" json:"label,omitempty"`
	AddedAt       string                 `protobuf:"bytes,15,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,16,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Files         []*TorrentFile         `protobuf:"bytes,17,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentInfo) Reset() {
	*x = TorrentInfo{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentInfo) ProtoMessage() {}

func (x *TorrentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentInfo.ProtoReflect.Descriptor instead.
func (*TorrentInfo) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{8}
}

func (x *TorrentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TorrentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TorrentInfo) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

func (x *TorrentInfo) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *TorrentInfo) GetDownloaded() int64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *TorrentInfo) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TorrentInfo) GetPeers() int32 {
	if x != nil {
		return x.Peers
	}
	return 0
}

func (x *TorrentInfo) GetSeeders() int32 {
	if x != nil {
		return x.Seeders
	}
	return 0
}

func (x *TorrentInfo) GetUploadRate() int32 {
	if x != nil {
		return x.UploadRate
	}
	return 0
}

func (x *TorrentInfo) GetDownloadRate() int32 {
	if x != nil {
		return x.DownloadRate
	}
	return 0
}

func (x *TorrentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TorrentInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TorrentInfo) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *TorrentInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TorrentInfo) GetAddedAt() string {
	if x != nil {
		return x.AddedAt
	}
	return ""
}

func (x *TorrentInfo) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *TorrentInfo) GetFiles() []*TorrentFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type TorrentFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Downloaded    int64                  `protobuf:"varint,3,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentFile) Reset() {
	*x = TorrentFile{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentFile) ProtoMessage() {}

func (x *TorrentFile) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentFile.ProtoReflect.Descriptor instead.
func (*TorrentFile) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{9}
}

func (x *TorrentFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TorrentFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TorrentFile) GetDownloaded() int64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

type VpnStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnStatusRequest) Reset() {
	*x = VpnStatusRequest{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnStatusRequest) ProtoMessage() {}

func (x *VpnStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnStatusRequest.ProtoReflect.Descriptor instead.
func (*VpnStatusRequest) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{10}
}

type VpnStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Connected         bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	InterfaceName     string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	LocalIp           string                 `protobuf:"bytes,3,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	GatewayIp         string                 `protobuf:"bytes,4,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	ConfigFile        string                 `protobuf:"bytes,5,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"`
	ConnectedAtUnix   int64                  `protobuf:"varint,6,opt,name=connected_at_unix,json=connectedAtUnix,proto3" json:"connected_at_unix,omitempty"`
	KillSwitchEnabled bool                   `protobuf:"varint,7,opt,name=kill_switch_enabled,json=killSwitchEnabled,proto3" json:"kill_switch_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VpnStatusResponse) Reset() {
	*x = VpnStatusResponse{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnStatusResponse) ProtoMessage() {}

func (x *VpnStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnStatusResponse.ProtoReflect.Descriptor instead.
func (*VpnStatusResponse) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{11}
}

func (x *VpnStatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *VpnStatusResponse) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *VpnStatusResponse) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *VpnStatusResponse) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *VpnStatusResponse) GetConfigFile() string {
	if x != nil {
		return x.ConfigFile
	}
	return ""
}

func (x *VpnStatusResponse) GetConnectedAtUnix() int64 {
	if x != nil {
		return x.ConnectedAtUnix
	}
	return 0
}

func (x *VpnStatusResponse) GetKillSwitchEnabled() bool {
	if x != nil {
		return x.KillSwitchEnabled
	}
	return false
}

type VpnStartRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfigFile        string                 `protobuf:"bytes,1,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"`
	EnableKillSwitch  bool                   `protobuf:"varint,2,opt,name=enable_kill_switch,json=enableKillSwitch,proto3" json:"enable_kill_switch,omitempty"`
	TorrentListenPort int32                  `protobuf:"varint,3,opt,name=torrent_listen_port,json=torrentListenPort,proto3" json:"torrent_listen_port,omitempty"`
	EnableNatPmp      bool                   `protobuf:"varint,4,opt,name=enable_nat_pmp,json=enableNatPmp,proto3" json:"enable_nat_pmp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VpnStartRequest) Reset() {
	*x = VpnStartRequest{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnStartRequest) ProtoMessage() {}

func (x *VpnStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnStartRequest.ProtoReflect.Descriptor instead.
func (*VpnStartRequest) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{12}
}

func (x *VpnStartRequest) GetConfigFile() string {
	if x != nil {
		return x.ConfigFile
	}
	return ""
}

func (x *VpnStartRequest) GetEnableKillSwitch() bool {
	if x != nil {
		return x.EnableKillSwitch
	}
	return false
}

func (x *VpnStartRequest) GetTorrentListenPort() int32 {
	if x != nil {
		return x.TorrentListenPort
	}
	return 0
}

func (x *VpnStartRequest) GetEnableNatPmp() bool {
	if x != nil {
		return x.EnableNatPmp
	}
	return false
}

type VpnStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	InterfaceName string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	LocalIp       string                 `protobuf:"bytes,3,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnStartResponse) Reset() {
	*x = VpnStartResponse{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnStartResponse) ProtoMessage() {}

func (x *VpnStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnStartResponse.ProtoReflect.Descriptor instead.
func (*VpnStartResponse) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{13}
}

func (x *VpnStartResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *VpnStartResponse) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *VpnStartResponse) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *VpnStartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VpnStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnStopRequest) Reset() {
	*x = VpnStopRequest{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnStopRequest) ProtoMessage() {}

func (x *VpnStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnStopRequest.ProtoReflect.Descriptor instead.
func (*VpnStopRequest) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{14}
}

type VpnStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnStopResponse) Reset() {
	*x = VpnStopResponse{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnStopResponse) ProtoMessage() {}

func (x *VpnStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnStopResponse.ProtoReflect.Descriptor instead.
func (*VpnStopResponse) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{15}
}

func (x *VpnStopResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type NatPmpStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NatPmpStatusRequest) Reset() {
	*x = NatPmpStatusRequest{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatPmpStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatPmpStatusRequest) ProtoMessage() {}

func (x *NatPmpStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatPmpStatusRequest.ProtoReflect.Descriptor instead.
func (*NatPmpStatusRequest) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{16}
}

type NatPmpStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	InternalPort    int32                  `protobuf:"varint,2,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	ExternalPort    int32                  `protobuf:"varint,3,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
	Protocol        string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	LifetimeSeconds int32                  `protobuf:"varint,5,opt,name=lifetime_seconds,json=lifetimeSeconds,proto3" json:"lifetime_seconds,omitempty"`
	MappedAtUnix    int64                  `protobuf:"varint,6,opt,name=mapped_at_unix,json=mappedAtUnix,proto3" json:"mapped_at_unix,omitempty"`
	Gateway         string                 `protobuf:"bytes,7,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NatPmpStatusResponse) Reset() {
	*x = NatPmpStatusResponse{}
	mi := &file_downloaderv1_downloader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatPmpStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatPmpStatusResponse) ProtoMessage() {}

func (x *NatPmpStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_downloaderv1_downloader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatPmpStatusResponse.ProtoReflect.Descriptor instead.
func (*NatPmpStatusResponse) Descriptor() ([]byte, []int) {
	return file_downloaderv1_downloader_proto_rawDescGZIP(), []int{17}
}

func (x *NatPmpStatusResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NatPmpStatusResponse) GetInternalPort() int32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *NatPmpStatusResponse) GetExternalPort() int32 {
	if x != nil {
		return x.ExternalPort
	}
	return 0
}

func (x *NatPmpStatusResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NatPmpStatusResponse) GetLifetimeSeconds() int32 {
	if x != nil {
		return x.LifetimeSeconds
	}
	return 0
}

func (x *NatPmpStatusResponse) GetMappedAtUnix() int64 {
	if x != nil {
		return x.MappedAtUnix
	}
	return 0
}

func (x *NatPmpStatusResponse) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

var File_downloaderv1_downloader_proto protoreflect.FileDescriptor

const file_downloaderv1_downloader_proto_rawDesc = "" +
	"\n" +
	"\x1ddownloaderv1/downloader.proto\x12\x15muxcore.downloader.v1\"p\n" +
	"\x11AddTorrentRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1b\n" +
	"\tsave_path\x18\x02 \x01(\tR\bsavePath\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x16\n" +
	"\x06paused\x18\x04 \x01(\bR\x06paused\"U\n" +
	"\x12AddTorrentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tinfo_hash\x18\x03 \x01(\tR\binfoHash\"I\n" +
	"\x14RemoveTorrentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdelete_files\x18\x02 \x01(\bR\vdeleteFiles\"\x17\n" +
	"\x15RemoveTorrentResponse\"#\n" +
	"\x11GetTorrentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x12GetTorrentResponse\x12<\n" +
	"\atorrent\x18\x01 \x01(\v2\".muxcore.downloader.v1.TorrentInfoR\atorrent\"-\n" +
	"\x13ListTorrentsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\"V\n" +
	"\x14ListTorrentsResponse\x12>\n" +
	"\btorrents\x18\x01 \x03(\v2\".muxcore.downloader.v1.TorrentInfoR\btorrents\"\xf8\x03\n" +
	"\vTorrentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tinfo_hash\x18\x03 \x01(\tR\binfoHash\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\x12\x1e\n" +
	"\n" +
	"downloaded\x18\x05 \x01(\x03R\n" +
	"downloaded\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x01R\bprogress\x12\x14\n" +
	"\x05peers\x18\a \x01(\x05R\x05peers\x12\x18\n" +
	"\aseeders\x18\b \x01(\x05R\aseeders\x12\x1f\n" +
	"\vupload_rate\x18\t \x01(\x05R\n" +
	"uploadRate\x12#\n" +
	"\rdownload_rate\x18\n" +
	" \x01(\x05R\fdownloadRate\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\x12\x1b\n" +
	"\tsave_path\x18\r \x01(\tR\bsavePath\x12\x14\n" +
	"\x05label\x18\x0e \x01(\tR\x05label\x12\x19\n" +
	"\badded_at\x18\x0f \x01(\tR\aaddedAt\x12!\n" +
	"\fcompleted_at\x18\x10 \x01(\tR\vcompletedAt\x128\n" +
	"\x05files\x18\x11 \x03(\v2\".muxcore.downloader.v1.TorrentFileR\x05files\"U\n" +
	"\vTorrentFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1e\n" +
	"\n" +
	"downloaded\x18\x03 \x01(\x03R\n" +
	"downloaded\"\x12\n" +
	"\x10VpnStatusRequest\"\x8f\x02\n" +
	"\x11VpnStatusResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x19\n" +
	"\blocal_ip\x18\x03 \x01(\tR\alocalIp\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x04 \x01(\tR\tgatewayIp\x12\x1f\n" +
	"\vconfig_file\x18\x05 \x01(\tR\n" +
	"configFile\x12*\n" +
	"\x11connected_at_unix\x18\x06 \x01(\x03R\x0fconnectedAtUnix\x12.\n" +
	"\x13kill_switch_enabled\x18\a \x01(\bR\x11killSwitchEnabled\"\xb6\x01\n" +
	"\x0fVpnStartRequest\x12\x1f\n" +
	"\vconfig_file\x18\x01 \x01(\tR\n" +
	"configFile\x12,\n" +
	"\x12enable_kill_switch\x18\x02 \x01(\bR\x10enableKillSwitch\x12.\n" +
	"\x13torrent_listen_port\x18\x03 \x01(\x05R\x11torrentListenPort\x12$\n" +
	"\x0eenable_nat_pmp\x18\x04 \x01(\bR\fenableNatPmp\"\x84\x01\n" +
	"\x10VpnStartResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x19\n" +
	"\blocal_ip\x18\x03 \x01(\tR\alocalIp\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x10\n" +
	"\x0eVpnStopRequest\"+\n" +
	"\x0fVpnStopResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\"\x15\n" +
	"\x13NatPmpStatusRequest\"\x81\x02\n" +
	"\x14NatPmpStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12#\n" +
	"\rinternal_port\x18\x02 \x01(\x05R\finternalPort\x12#\n" +
	"\rexternal_port\x18\x03 \x01(\x05R\fexternalPort\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12)\n" +
	"\x10lifetime_seconds\x18\x05 \x01(\x05R\x0flifetimeSeconds\x12$\n" +
	"\x0emapped_at_unix\x18\x06 \x01(\x03R\fmappedAtUnix\x12\x18\n" +
	"\agateway\x18\a \x01(\tR\agateway2\xab\x06\n" +
	"\x0eTorrentService\x12a\n" +
	"\n" +
	"AddTorrent\x12(.muxcore.downloader.v1.AddTorrentRequest\x1a).muxcore.downloader.v1.AddTorrentResponse\x12j\n" +
	"\rRemoveTorrent\x12+.muxcore.downloader.v1.RemoveTorrentRequest\x1a,.muxcore.downloader.v1.RemoveTorrentResponse\x12a\n" +
	"\n" +
	"GetTorrent\x12(.muxcore.downloader.v1.GetTorrentRequest\x1a).muxcore.downloader.v1.GetTorrentResponse\x12g\n" +
	"\fListTorrents\x12*.muxcore.downloader.v1.ListTorrentsRequest\x1a+.muxcore.downloader.v1.ListTorrentsResponse\x12^\n" +
	"\tVpnStatus\x12'.muxcore.downloader.v1.VpnStatusRequest\x1a(.muxcore.downloader.v1.VpnStatusResponse\x12[\n" +
	"\bVpnStart\x12&.muxcore.downloader.v1.VpnStartRequest\x1a'.muxcore.downloader.v1.VpnStartResponse\x12X\n" +
	"\aVpnStop\x12%.muxcore.downloader.v1.VpnStopRequest\x1a&.muxcore.downloader.v1.VpnStopResponse\x12g\n" +
	"\fNatPmpStatus\x12*.muxcore.downloader.v1.NatPmpStatusRequest\x1a+.muxcore.downloader.v1.NatPmpStatusResponseBTZRgithub.com/Muxcore-Media/downloader-native-torrent/proto/downloaderv1;downloaderv1b\x06proto3"

var (
	file_downloaderv1_downloader_proto_rawDescOnce sync.Once
	file_downloaderv1_downloader_proto_rawDescData []byte
)

func file_downloaderv1_downloader_proto_rawDescGZIP() []byte {
	file_downloaderv1_downloader_proto_rawDescOnce.Do(func() {
		file_downloaderv1_downloader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_downloaderv1_downloader_proto_rawDesc), len(file_downloaderv1_downloader_proto_rawDesc)))
	})
	return file_downloaderv1_downloader_proto_rawDescData
}

var file_downloaderv1_downloader_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_downloaderv1_downloader_proto_goTypes = []any{
	(*AddTorrentRequest)(nil),     // 0: muxcore.downloader.v1.AddTorrentRequest
	(*AddTorrentResponse)(nil),    // 1: muxcore.downloader.v1.AddTorrentResponse
	(*RemoveTorrentRequest)(nil),  // 2: muxcore.downloader.v1.RemoveTorrentRequest
	(*RemoveTorrentResponse)(nil), // 3: muxcore.downloader.v1.RemoveTorrentResponse
	(*GetTorrentRequest)(nil),     // 4: muxcore.downloader.v1.GetTorrentRequest
	(*GetTorrentResponse)(nil),    // 5: muxcore.downloader.v1.GetTorrentResponse
	(*ListTorrentsRequest)(nil),   // 6: muxcore.downloader.v1.ListTorrentsRequest
	(*ListTorrentsResponse)(nil),  // 7: muxcore.downloader.v1.ListTorrentsResponse
	(*TorrentInfo)(nil),           // 8: muxcore.downloader.v1.TorrentInfo
	(*TorrentFile)(nil),           // 9: muxcore.downloader.v1.TorrentFile
	(*VpnStatusRequest)(nil),      // 10: muxcore.downloader.v1.VpnStatusRequest
	(*VpnStatusResponse)(nil),     // 11: muxcore.downloader.v1.VpnStatusResponse
	(*VpnStartRequest)(nil),       // 12: muxcore.downloader.v1.VpnStartRequest
	(*VpnStartResponse)(nil),      // 13: muxcore.downloader.v1.VpnStartResponse
	(*VpnStopRequest)(nil),        // 14: muxcore.downloader.v1.VpnStopRequest
	(*VpnStopResponse)(nil),       // 15: muxcore.downloader.v1.VpnStopResponse
	(*NatPmpStatusRequest)(nil),   // 16: muxcore.downloader.v1.NatPmpStatusRequest
	(*NatPmpStatusResponse)(nil),  // 17: muxcore.downloader.v1.NatPmpStatusResponse
}
var file_downloaderv1_downloader_proto_depIdxs = []int32{
	8,  // 0: muxcore.downloader.v1.GetTorrentResponse.torrent:type_name -> muxcore.downloader.v1.TorrentInfo
	8,  // 1: muxcore.downloader.v1.ListTorrentsResponse.torrents:type_name -> muxcore.downloader.v1.TorrentInfo
	9,  // 2: muxcore.downloader.v1.TorrentInfo.files:type_name -> muxcore.downloader.v1.TorrentFile
	0,  // 3: muxcore.downloader.v1.TorrentService.AddTorrent:input_type -> muxcore.downloader.v1.AddTorrentRequest
	2,  // 4: muxcore.downloader.v1.TorrentService.RemoveTorrent:input_type -> muxcore.downloader.v1.RemoveTorrentRequest
	4,  // 5: muxcore.downloader.v1.TorrentService.GetTorrent:input_type -> muxcore.downloader.v1.GetTorrentRequest
	6,  // 6: muxcore.downloader.v1.TorrentService.ListTorrents:input_type -> muxcore.downloader.v1.ListTorrentsRequest
	10, // 7: muxcore.downloader.v1.TorrentService.VpnStatus:input_type -> muxcore.downloader.v1.VpnStatusRequest
	12, // 8: muxcore.downloader.v1.TorrentService.VpnStart:input_type -> muxcore.downloader.v1.VpnStartRequest
	14, // 9: muxcore.downloader.v1.TorrentService.VpnStop:input_type -> muxcore.downloader.v1.VpnStopRequest
	16, // 10: muxcore.downloader.v1.TorrentService.NatPmpStatus:input_type -> muxcore.downloader.v1.NatPmpStatusRequest
	1,  // 11: muxcore.downloader.v1.TorrentService.AddTorrent:output_type -> muxcore.downloader.v1.AddTorrentResponse
	3,  // 12: muxcore.downloader.v1.TorrentService.RemoveTorrent:output_type -> muxcore.downloader.v1.RemoveTorrentResponse
	5,  // 13: muxcore.downloader.v1.TorrentService.GetTorrent:output_type -> muxcore.downloader.v1.GetTorrentResponse
	7,  // 14: muxcore.downloader.v1.TorrentService.ListTorrents:output_type -> muxcore.downloader.v1.ListTorrentsResponse
	11, // 15: muxcore.downloader.v1.TorrentService.VpnStatus:output_type -> muxcore.downloader.v1.VpnStatusResponse
	13, // 16: muxcore.downloader.v1.TorrentService.VpnStart:output_type -> muxcore.downloader.v1.VpnStartResponse
	15, // 17: muxcore.downloader.v1.TorrentService.VpnStop:output_type -> muxcore.downloader.v1.VpnStopResponse
	17, // 18: muxcore.downloader.v1.TorrentService.NatPmpStatus:output_type -> muxcore.downloader.v1.NatPmpStatusResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_downloaderv1_downloader_proto_init() }
func file_downloaderv1_downloader_proto_init() {
	if File_downloaderv1_downloader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_downloaderv1_downloader_proto_rawDesc), len(file_downloaderv1_downloader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_downloaderv1_downloader_proto_goTypes,
		DependencyIndexes: file_downloaderv1_downloader_proto_depIdxs,
		MessageInfos:      file_downloaderv1_downloader_proto_msgTypes,
	}.Build()
	File_downloaderv1_downloader_proto = out.File
	file_downloaderv1_downloader_proto_goTypes = nil
	file_downloaderv1_downloader_proto_depIdxs = nil
}
