// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: downloaderv1/downloader.proto

package downloaderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TorrentService_AddTorrent_FullMethodName    = "/muxcore.downloader.v1.TorrentService/AddTorrent"
	TorrentService_RemoveTorrent_FullMethodName = "/muxcore.downloader.v1.TorrentService/RemoveTorrent"
	TorrentService_GetTorrent_FullMethodName    = "/muxcore.downloader.v1.TorrentService/GetTorrent"
	TorrentService_ListTorrents_FullMethodName  = "/muxcore.downloader.v1.TorrentService/ListTorrents"
	TorrentService_VpnStatus_FullMethodName     = "/muxcore.downloader.v1.TorrentService/VpnStatus"
	TorrentService_VpnStart_FullMethodName      = "/muxcore.downloader.v1.TorrentService/VpnStart"
	TorrentService_VpnStop_FullMethodName       = "/muxcore.downloader.v1.TorrentService/VpnStop"
	TorrentService_NatPmpStatus_FullMethodName  = "/muxcore.downloader.v1.TorrentService/NatPmpStatus"
)

// TorrentServiceClient is the client API for TorrentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TorrentServiceClient interface {
	AddTorrent(ctx context.Context, in *AddTorrentRequest, opts ...grpc.CallOption) (*AddTorrentResponse, error)
	RemoveTorrent(ctx context.Context, in *RemoveTorrentRequest, opts ...grpc.CallOption) (*RemoveTorrentResponse, error)
	GetTorrent(ctx context.Context, in *GetTorrentRequest, opts ...grpc.CallOption) (*GetTorrentResponse, error)
	ListTorrents(ctx context.Context, in *ListTorrentsRequest, opts ...grpc.CallOption) (*ListTorrentsResponse, error)
	VpnStatus(ctx context.Context, in *VpnStatusRequest, opts ...grpc.CallOption) (*VpnStatusResponse, error)
	VpnStart(ctx context.Context, in *VpnStartRequest, opts ...grpc.CallOption) (*VpnStartResponse, error)
	VpnStop(ctx context.Context, in *VpnStopRequest, opts ...grpc.CallOption) (*VpnStopResponse, error)
	NatPmpStatus(ctx context.Context, in *NatPmpStatusRequest, opts ...grpc.CallOption) (*NatPmpStatusResponse, error)
}

type torrentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTorrentServiceClient(cc grpc.ClientConnInterface) TorrentServiceClient {
	return &torrentServiceClient{cc}
}

func (c *torrentServiceClient) AddTorrent(ctx context.Context, in *AddTorrentRequest, opts ...grpc.CallOption) (*AddTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTorrentResponse)
	err := c.cc.Invoke(ctx, TorrentService_AddTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentServiceClient) RemoveTorrent(ctx context.Context, in *RemoveTorrentRequest, opts ...grpc.CallOption) (*RemoveTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTorrentResponse)
	err := c.cc.Invoke(ctx, TorrentService_RemoveTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentServiceClient) GetTorrent(ctx context.Context, in *GetTorrentRequest, opts ...grpc.CallOption) (*GetTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTorrentResponse)
	err := c.cc.Invoke(ctx, TorrentService_GetTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentServiceClient) ListTorrents(ctx context.Context, in *ListTorrentsRequest, opts ...grpc.CallOption) (*ListTorrentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTorrentsResponse)
	err := c.cc.Invoke(ctx, TorrentService_ListTorrents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentServiceClient) VpnStatus(ctx context.Context, in *VpnStatusRequest, opts ...grpc.CallOption) (*VpnStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VpnStatusResponse)
	err := c.cc.Invoke(ctx, TorrentService_VpnStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentServiceClient) VpnStart(ctx context.Context, in *VpnStartRequest, opts ...grpc.CallOption) (*VpnStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VpnStartResponse)
	err := c.cc.Invoke(ctx, TorrentService_VpnStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentServiceClient) VpnStop(ctx context.Context, in *VpnStopRequest, opts ...grpc.CallOption) (*VpnStopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VpnStopResponse)
	err := c.cc.Invoke(ctx, TorrentService_VpnStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentServiceClient) NatPmpStatus(ctx context.Context, in *NatPmpStatusRequest, opts ...grpc.CallOption) (*NatPmpStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NatPmpStatusResponse)
	err := c.cc.Invoke(ctx, TorrentService_NatPmpStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TorrentServiceServer is the server API for TorrentService service.
// All implementations must embed UnimplementedTorrentServiceServer
// for forward compatibility.
type TorrentServiceServer interface {
	AddTorrent(context.Context, *AddTorrentRequest) (*AddTorrentResponse, error)
	RemoveTorrent(context.Context, *RemoveTorrentRequest) (*RemoveTorrentResponse, error)
	GetTorrent(context.Context, *GetTorrentRequest) (*GetTorrentResponse, error)
	ListTorrents(context.Context, *ListTorrentsRequest) (*ListTorrentsResponse, error)
	VpnStatus(context.Context, *VpnStatusRequest) (*VpnStatusResponse, error)
	VpnStart(context.Context, *VpnStartRequest) (*VpnStartResponse, error)
	VpnStop(context.Context, *VpnStopRequest) (*VpnStopResponse, error)
	NatPmpStatus(context.Context, *NatPmpStatusRequest) (*NatPmpStatusResponse, error)
	mustEmbedUnimplementedTorrentServiceServer()
}

// UnimplementedTorrentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTorrentServiceServer struct{}

func (UnimplementedTorrentServiceServer) AddTorrent(context.Context, *AddTorrentRequest) (*AddTorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTorrent not implemented")
}
func (UnimplementedTorrentServiceServer) RemoveTorrent(context.Context, *RemoveTorrentRequest) (*RemoveTorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTorrent not implemented")
}
func (UnimplementedTorrentServiceServer) GetTorrent(context.Context, *GetTorrentRequest) (*GetTorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTorrent not implemented")
}
func (UnimplementedTorrentServiceServer) ListTorrents(context.Context, *ListTorrentsRequest) (*ListTorrentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTorrents not implemented")
}
func (UnimplementedTorrentServiceServer) VpnStatus(context.Context, *VpnStatusRequest) (*VpnStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VpnStatus not implemented")
}
func (UnimplementedTorrentServiceServer) VpnStart(context.Context, *VpnStartRequest) (*VpnStartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VpnStart not implemented")
}
func (UnimplementedTorrentServiceServer) VpnStop(context.Context, *VpnStopRequest) (*VpnStopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VpnStop not implemented")
}
func (UnimplementedTorrentServiceServer) NatPmpStatus(context.Context, *NatPmpStatusRequest) (*NatPmpStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NatPmpStatus not implemented")
}
func (UnimplementedTorrentServiceServer) mustEmbedUnimplementedTorrentServiceServer() {}
func (UnimplementedTorrentServiceServer) testEmbeddedByValue()                        {}

// UnsafeTorrentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TorrentServiceServer will
// result in compilation errors.
type UnsafeTorrentServiceServer interface {
	mustEmbedUnimplementedTorrentServiceServer()
}

func RegisterTorrentServiceServer(s grpc.ServiceRegistrar, srv TorrentServiceServer) {
	// If the following call panics, it indicates UnimplementedTorrentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TorrentService_ServiceDesc, srv)
}

func _TorrentService_AddTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).AddTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_AddTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).AddTorrent(ctx, req.(*AddTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentService_RemoveTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).RemoveTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_RemoveTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).RemoveTorrent(ctx, req.(*RemoveTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentService_GetTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).GetTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_GetTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).GetTorrent(ctx, req.(*GetTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentService_ListTorrents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTorrentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).ListTorrents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_ListTorrents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).ListTorrents(ctx, req.(*ListTorrentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentService_VpnStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpnStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).VpnStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_VpnStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).VpnStatus(ctx, req.(*VpnStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentService_VpnStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpnStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).VpnStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_VpnStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).VpnStart(ctx, req.(*VpnStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentService_VpnStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpnStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).VpnStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_VpnStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).VpnStop(ctx, req.(*VpnStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentService_NatPmpStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NatPmpStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).NatPmpStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_NatPmpStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).NatPmpStatus(ctx, req.(*NatPmpStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TorrentService_ServiceDesc is the grpc.ServiceDesc for TorrentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TorrentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.downloader.v1.TorrentService",
	HandlerType: (*TorrentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTorrent",
			Handler:    _TorrentService_AddTorrent_Handler,
		},
		{
			MethodName: "RemoveTorrent",
			Handler:    _TorrentService_RemoveTorrent_Handler,
		},
		{
			MethodName: "GetTorrent",
			Handler:    _TorrentService_GetTorrent_Handler,
		},
		{
			MethodName: "ListTorrents",
			Handler:    _TorrentService_ListTorrents_Handler,
		},
		{
			MethodName: "VpnStatus",
			Handler:    _TorrentService_VpnStatus_Handler,
		},
		{
			MethodName: "VpnStart",
			Handler:    _TorrentService_VpnStart_Handler,
		},
		{
			MethodName: "VpnStop",
			Handler:    _TorrentService_VpnStop_Handler,
		},
		{
			MethodName: "NatPmpStatus",
			Handler:    _TorrentService_NatPmpStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "downloaderv1/downloader.proto",
}
